services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/app.py
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_TEST_DATABASE=${MYSQL_TEST_DATABASE}
    command: python -m flask run --host=0.0.0.0 --port=5000 --reload
    depends_on:
      - minio
      - mysql
    networks:
      - appnetwork

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public      
    command: ["npm", "run", "dev"]
    depends_on:
      - backend
    networks:
      - appnetwork

    
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - 'minio_data:/data'
    networks:
      - appnetwork

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/sql/01-init.sql:/docker-entrypoint-initdb.d/01-init.sql    
      - ./db/sql/02-init_data.sql:/docker-entrypoint-initdb.d/02-init_data.sql
      - ./db/sql/03-init_test.sql:/docker-entrypoint-initdb.d/03-init_test.sql
    networks:
      - appnetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    networks:
      - appnetwork
  tests:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - PYTHONPATH=/app/src
      - FLASK_ENV=testing
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_TEST_DATABASE=${MYSQL_TEST_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    depends_on:
      - mysql
    networks:
      - appnetwork
    command: ["tail", "-f", "/dev/null"]  

networks:
  appnetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local
  mysql_data:
    driver: local