services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=src/app.py
      - MONGO_URI=mongodb://mongo:27017/
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ROOT_USER=user
      - MINIO_ROOT_PASSWORD=1234
    command: python -m flask run --host=0.0.0.0 --port=5000 --reload
    depends_on:
      - mongo
      - minio
    networks:
      - appnetwork

  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - appnetwork
    
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=8yg89dfsygfgyy9ys98fdg
    volumes:
      - 'minio_data:/data'
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge

volumes:
  mongo_data:
  minio_data:
    driver: local
